### ISSUE TITLE
daq backend starts immediately in allinone launcher

### ISSUE THREAD

**Issue by nzjrs** [murthylab/fly-vr#9]
or at least the accounting of when things occur is incorrect?

because of how the `data_generator` works, maybe we have to `signal_new_playlist_item` before the chunk is callback'd to the daq buffer?

retroduce
```
configuration:
  analog_in_channels:
    0: 'Sound'
    1: 'Copy of AO0'
  analog_out_channels:
    0: 'Opto'
  projector_disable: true
  fictrac_config: 'C:/Users/John Stowers/Downloads/Dudi_ShareWithJohn_flyVR/DSX_VR2P_IPIshort_2018/180719_103/180719_103_output.h5'
  delay: 3
playlist:
  daq:
  - Delay-1s:
      attenuator: null
      amplitude: 0.0
      duration: 1000
      name: constant
      post_silence: 0
      pre_silence: 0
      sample_rate: 10000
  - Opto1090-9-1:
      amplitude_a: 9.0
      duration_a: 1000
      amplitude_b: 0.0
      duration_b: 2000
      name: pulse
      post_silence: 1000
      pre_silence: 1000
      sample_rate: 10000
```

notice that in the toc file Opto1090-9-1 plays immediately after Delay

```
- {"item": "Delay-1s", "backend": "daq", "sound_output_num_samples_written": 0, "video_output_num_frames": 0, "daq_output_num_samples_written": 5000, "fictrac_frame_num": 4850}
- {"item": "Opto1090-9-1", "backend": "daq", "sound_output_num_samples_written": 0, "video_output_num_frames": 0, "daq_output_num_samples_written": 15000, "fictrac_frame_num": 4852}
```
